// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1oZwElkgoch609ePyS0WwqiqGmlOzPqw',
    appId: '1:354943326959:web:8f32179e1300f2f729d91a',
    messagingSenderId: '354943326959',
    projectId: 'startup-namer-bdfd9',
    authDomain: 'startup-namer-bdfd9.firebaseapp.com',
    storageBucket: 'startup-namer-bdfd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmo0ddSrKeHaOWgTHQ-TbyjxYrMGSYgrU',
    appId: '1:354943326959:android:8f3217817f70804529d91a',
    messagingSenderId: '354943326959',
    projectId: 'startup-namer-bdfd9',
    storageBucket: 'startup-namer-bdfd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXRZFtMcRW3a--QE7Y-cDqiuFOOP-rms',
    appId: '1:354943326959:ios:ed1e89b0ca2874c329d91a',
    messagingSenderId: '354943326959',
    projectId: 'startup-namer-bdfd9',
    storageBucket: 'startup-namer-bdfd9.appspot.com',
    iosClientId: '354943326959-d3c02ajc0tkrce1i8kn7o0nlnrmp6hp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.davidApp',
  );
}
